/**
 * The design of an exported document: type, colour and layout choices that
 * every exporter honours, so Word, PDF, HTML and PowerPoint come out looking
 * like the same document.
 */
export interface DocTheme {
  preset: string;
  accent: string;
  /** Keys into FONTS. */
  headingFont: string;
  bodyFont: string;
  /** Body size in points. */
  fontSize: number;
  lineHeight: number;
  justify: boolean;
  headingRule: boolean;
  coverStyle: "centered" | "band" | "minimal";
  tableStyle: "filled" | "lines";
  pageSize: "a4" | "letter";
  margin: "narrow" | "normal" | "wide";
}

export interface FontChoice {
  id: string;
  ar: string;
  en: string;
  /**
   * What the face is fit for. Display faces are beautiful at 30pt and
   * unreadable in a paragraph, so the picker keeps them out of the body slot.
   */
  role?: "heading" | "body" | "both";
  /** Which script the face is chosen for; the picker groups by it. */
  script?: "ar" | "la";
  /** Broad shape, for grouping and for sensible theme pairing. */
  kind?: "serif" | "sans" | "calligraphic" | "display";
  /** CSS stack for HTML and PDF. */
  css: string;
  /** The nearest font Word actually has installed. */
  word: string;
  /** Google Fonts family to request, if any. */
  google?: string;
}

export const FONTS: FontChoice[] = [
  {
    id: "naskh",
    ar: "أميري (نسخ)",
    en: "Amiri",
    role: "both",
    script: "ar",
    kind: "serif",
    css: '"Amiri",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Amiri:wght@400;700",
  },
  {
    id: "plex",
    ar: "IBM Plex عربي",
    en: "IBM Plex Sans Arabic",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"IBM Plex Sans Arabic","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "IBM+Plex+Sans+Arabic:wght@300;400;500;600;700",
  },
  {
    id: "cairo",
    ar: "القاهرة",
    en: "Cairo",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Cairo","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Cairo:wght@300;400;500;600;700",
  },
  {
    id: "tajawal",
    ar: "تجوّل",
    en: "Tajawal",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Tajawal","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Tajawal:wght@300;400;500;700",
  },
  {
    id: "almarai",
    ar: "المراعي",
    en: "Almarai",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Almarai","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Almarai:wght@300;400;700",
  },
  {
    id: "notonaskh",
    ar: "نوتو نسخ",
    en: "Noto Naskh Arabic",
    role: "both",
    script: "ar",
    kind: "serif",
    css: '"Noto Naskh Arabic",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Noto+Naskh+Arabic:wght@400;500;600;700",
  },
  {
    id: "notosans",
    ar: "نوتو عربي",
    en: "Noto Sans Arabic",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Noto Sans Arabic","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Noto+Sans+Arabic:wght@300;400;500;600;700",
  },
  {
    id: "notokufi",
    ar: "نوتو كوفي",
    en: "Noto Kufi Arabic",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Noto Kufi Arabic","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Noto+Kufi+Arabic:wght@400;500;600;700",
  },
  {
    id: "changa",
    ar: "تشانجا",
    en: "Changa",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Changa","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Changa:wght@400;500;600;700",
  },
  {
    id: "messiri",
    ar: "المسيري",
    en: "El Messiri",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"El Messiri","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "El+Messiri:wght@400;500;600;700",
  },
  {
    id: "reemkufi",
    ar: "ريم كوفي",
    en: "Reem Kufi",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Reem Kufi","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Reem+Kufi:wght@400;500;600;700",
  },
  {
    id: "markazi",
    ar: "مركزي",
    en: "Markazi Text",
    role: "both",
    script: "ar",
    kind: "serif",
    css: '"Markazi Text",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "Markazi+Text:wght@400;500;600;700",
  },
  {
    id: "scheherazade",
    ar: "شهرزاد",
    en: "Scheherazade New",
    role: "body",
    script: "ar",
    kind: "serif",
    css: '"Scheherazade New",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Scheherazade+New:wght@400;500;600;700",
  },
  {
    id: "readex",
    ar: "ريدكس برو",
    en: "Readex Pro",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Readex Pro","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Readex+Pro:wght@300;400;500;600;700",
  },
  {
    id: "alexandria",
    ar: "الإسكندرية",
    en: "Alexandria",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Alexandria","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Alexandria:wght@300;400;500;600;700",
  },
  {
    id: "kufam",
    ar: "كُفام",
    en: "Kufam",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Kufam","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Kufam:wght@400;500;600;700",
  },
  {
    id: "mada",
    ar: "مدى",
    en: "Mada",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Mada","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Mada:wght@300;400;500;600;700",
  },
  {
    id: "arefruqaa",
    ar: "عارف رقعة",
    en: "Aref Ruqaa",
    role: "heading",
    script: "ar",
    kind: "calligraphic",
    css: '"Aref Ruqaa","Arabic Typesetting",Georgia,serif',
    word: "Arabic Typesetting",
    google: "Aref+Ruqaa:wght@400;700",
  },
  {
    id: "alkalami",
    ar: "الكلمي",
    en: "Alkalami",
    role: "heading",
    script: "ar",
    kind: "serif",
    css: '"Alkalami",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Alkalami:wght@400",
  },
  {
    id: "baloo",
    ar: "بالو بهائجان",
    en: "Baloo Bhaijaan 2",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Baloo Bhaijaan 2","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Baloo+Bhaijaan+2:wght@400;500;600;700",
  },
  {
    id: "beiruti",
    ar: "بيروتي",
    en: "Beiruti",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Beiruti","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Beiruti:wght@300;400;500;600;700",
  },
  {
    id: "estedad",
    ar: "استعداد",
    en: "Estedad",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Estedad","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Estedad:wght@300;400;500;600;700",
  },
  {
    id: "fustat",
    ar: "الفسطاط",
    en: "Fustat",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Fustat","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Fustat:wght@300;400;500;600;700",
  },
  {
    id: "gulzar",
    ar: "گلزار",
    en: "Gulzar",
    role: "heading",
    script: "ar",
    kind: "serif",
    css: '"Gulzar",Georgia,"Times New Roman",serif',
    word: "Arabic Typesetting",
    google: "Gulzar:wght@400",
  },
  {
    id: "harmattan",
    ar: "هرمتان",
    en: "Harmattan",
    role: "body",
    script: "ar",
    kind: "sans",
    css: '"Harmattan","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Harmattan:wght@400;500;600;700",
  },
  {
    id: "katibeh",
    ar: "كتيبة",
    en: "Katibeh",
    role: "heading",
    script: "ar",
    kind: "calligraphic",
    css: '"Katibeh","Arabic Typesetting",Georgia,serif',
    word: "Arabic Typesetting",
    google: "Katibeh:wght@400",
  },
  {
    id: "lalezar",
    ar: "لاله‌زار",
    en: "Lalezar",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Lalezar","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Lalezar:wght@400",
  },
  {
    id: "lateef",
    ar: "لطيف",
    en: "Lateef",
    role: "body",
    script: "ar",
    kind: "serif",
    css: '"Lateef",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Lateef:wght@300;400;500;600;700",
  },
  {
    id: "lemonada",
    ar: "ليمونادة",
    en: "Lemonada",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Lemonada","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Lemonada:wght@400;500;600;700",
  },
  {
    id: "marhey",
    ar: "مرحى",
    en: "Marhey",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Marhey","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Marhey:wght@400;500;600;700",
  },
  {
    id: "mirza",
    ar: "ميرزا",
    en: "Mirza",
    role: "heading",
    script: "ar",
    kind: "serif",
    css: '"Mirza",Georgia,"Times New Roman",serif',
    word: "Arabic Typesetting",
    google: "Mirza:wght@400;500;600;700",
  },
  {
    id: "qahiri",
    ar: "قاهري",
    en: "Qahiri",
    role: "heading",
    script: "ar",
    kind: "sans",
    css: '"Qahiri","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Qahiri:wght@400",
  },
  {
    id: "rakkas",
    ar: "رقّاص",
    en: "Rakkas",
    role: "heading",
    script: "ar",
    kind: "display",
    css: '"Rakkas","Arabic Typesetting",Georgia,serif',
    word: "Arabic Typesetting",
    google: "Rakkas:wght@400",
  },
  {
    id: "rubik",
    ar: "روبيك",
    en: "Rubik",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Rubik","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Rubik:wght@300;400;500;600;700",
  },
  {
    id: "ruwudu",
    ar: "رُوودو",
    en: "Ruwudu",
    role: "both",
    script: "ar",
    kind: "serif",
    css: '"Ruwudu",Georgia,"Times New Roman",serif',
    word: "Traditional Arabic",
    google: "Ruwudu:wght@400;500;600;700",
  },
  {
    id: "vazirmatn",
    ar: "وزیرمتن",
    en: "Vazirmatn",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Vazirmatn","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Vazirmatn:wght@300;400;500;600;700",
  },
  {
    id: "zain",
    ar: "زين",
    en: "Zain",
    role: "both",
    script: "ar",
    kind: "sans",
    css: '"Zain","Segoe UI",Tahoma,sans-serif',
    word: "Arial",
    google: "Zain:wght@300;400;700",
  },
  {
    id: "serif",
    ar: "سيريف لاتيني",
    en: "Source Serif 4",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Source Serif 4",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "Source+Serif+4:wght@300;400;500;600;700",
  },
  {
    id: "alegreya",
    ar: "أليجريا",
    en: "Alegreya",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Alegreya",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Alegreya:wght@400;500;600;700",
  },
  {
    id: "bitter",
    ar: "بِتر",
    en: "Bitter",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Bitter",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Bitter:wght@300;400;500;600;700",
  },
  {
    id: "cardo",
    ar: "كاردو",
    en: "Cardo",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Cardo",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "Cardo:wght@400;700",
  },
  {
    id: "crimson",
    ar: "كريمسون",
    en: "Crimson Pro",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Crimson Pro",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "Crimson+Pro:wght@300;400;500;600;700",
  },
  {
    id: "ebgaramond",
    ar: "جارامون",
    en: "EB Garamond",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"EB Garamond",Georgia,"Times New Roman",serif',
    word: "Garamond",
    google: "EB+Garamond:wght@400;500;600;700",
  },
  {
    id: "plexserif",
    ar: "IBM Plex سيريف",
    en: "IBM Plex Serif",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"IBM Plex Serif",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "IBM+Plex+Serif:wght@300;400;500;600;700",
  },
  {
    id: "inter",
    ar: "إنتر",
    en: "Inter",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Inter","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Inter:wght@300;400;500;600;700",
  },
  {
    id: "karla",
    ar: "كارلا",
    en: "Karla",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Karla","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Karla:wght@300;400;500;600;700",
  },
  {
    id: "baskerville",
    ar: "باسكرفيل",
    en: "Libre Baskerville",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Libre Baskerville",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Libre+Baskerville:wght@400;500;600;700",
  },
  {
    id: "lora",
    ar: "لورا",
    en: "Lora",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Lora",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Lora:wght@400;500;600;700",
  },
  {
    id: "manrope",
    ar: "مانروب",
    en: "Manrope",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Manrope","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Manrope:wght@300;400;500;600;700",
  },
  {
    id: "merriweather",
    ar: "ميريويذر",
    en: "Merriweather",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Merriweather",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Merriweather:wght@300;400;500;600;700",
  },
  {
    id: "notoserif",
    ar: "نوتو سيريف",
    en: "Noto Serif",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Noto Serif",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "Noto+Serif:wght@300;400;500;600;700",
  },
  {
    id: "ptserif",
    ar: "PT سيريف",
    en: "PT Serif",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"PT Serif",Georgia,"Times New Roman",serif',
    word: "Times New Roman",
    google: "PT+Serif:wght@400;700",
  },
  {
    id: "playfair",
    ar: "بلايفير",
    en: "Playfair Display",
    role: "heading",
    script: "la",
    kind: "serif",
    css: '"Playfair Display",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Playfair+Display:wght@400;500;600;700",
  },
  {
    id: "publicsans",
    ar: "بابليك سانس",
    en: "Public Sans",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Public Sans","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Public+Sans:wght@300;400;500;600;700",
  },
  {
    id: "robotoslab",
    ar: "روبوتو سلاب",
    en: "Roboto Slab",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Roboto Slab",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Roboto+Slab:wght@300;400;500;600;700",
  },
  {
    id: "sourcesans",
    ar: "سورس سانس",
    en: "Source Sans 3",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Source Sans 3","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Source+Sans+3:wght@300;400;500;600;700",
  },
  {
    id: "spectral",
    ar: "سبكترال",
    en: "Spectral",
    role: "both",
    script: "la",
    kind: "serif",
    css: '"Spectral",Georgia,"Times New Roman",serif',
    word: "Georgia",
    google: "Spectral:wght@300;400;500;600;700",
  },
  {
    id: "worksans",
    ar: "وورك سانس",
    en: "Work Sans",
    role: "both",
    script: "la",
    kind: "sans",
    css: '"Work Sans","Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
    google: "Work+Sans:wght@300;400;500;600;700",
  },
  {
    id: "system",
    ar: "افتراضي النظام",
    en: "System default",
    role: "both",
    script: "la",
    kind: "sans",
    css: 'system-ui,"Segoe UI",Tahoma,sans-serif',
    word: "Calibri",
  },
];

export const fontById = (id: string): FontChoice =>
  FONTS.find((f) => f.id === id) ?? FONTS[1];

/**
 * Every accent is checked against the three pairings the exporters actually
 * produce — white text on the accent, accent text on its own 6% wash, and
 * body ink on that wash — and clears WCAG AA (4.5:1) on all three. Adding
 * one without checking is how a theme ends up unreadable on a projector.
 */
export const ACCENTS = [
  { id: "navy", hex: "#1F3864", ar: "كحلي", en: "Navy" },
  { id: "teal", hex: "#0D6A6F", ar: "أزرق مخضر", en: "Teal" },
  { id: "maroon", hex: "#7B2D3B", ar: "عنّابي", en: "Maroon" },
  { id: "forest", hex: "#1F5136", ar: "أخضر داكن", en: "Forest" },
  { id: "graphite", hex: "#2E3440", ar: "رمادي فحمي", en: "Graphite" },
  { id: "indigo", hex: "#3A3D8F", ar: "نيلي", en: "Indigo" },
  { id: "plum", hex: "#5B2A6B", ar: "برقوقي", en: "Plum" },
  { id: "rust", hex: "#8A3B12", ar: "صدئي", en: "Rust" },
  { id: "ocean", hex: "#12506E", ar: "أزرق محيطي", en: "Ocean" },
  { id: "olive", hex: "#4A5320", ar: "زيتوني", en: "Olive" },
  { id: "slate", hex: "#334155", ar: "أردوازي", en: "Slate" },
  { id: "burgundy", hex: "#5F1F35", ar: "خمري", en: "Burgundy" },
  { id: "pine", hex: "#14532D", ar: "صنوبري", en: "Pine" },
  { id: "sand", hex: "#7A5B1E", ar: "رملي", en: "Sand" },
  { id: "violet", hex: "#4C2A85", ar: "بنفسجي", en: "Violet" },
  { id: "cobalt", hex: "#1D4ED8", ar: "كوبالت", en: "Cobalt" },
  { id: "crimson", hex: "#9B1C31", ar: "قرمزي", en: "Crimson" },
  { id: "cyan", hex: "#0E5C63", ar: "تركوازي داكن", en: "Deep cyan" },
  { id: "aubergine", hex: "#4A1D4E", ar: "باذنجاني", en: "Aubergine" },
  { id: "moss", hex: "#3F5233", ar: "طحلبي", en: "Moss" },
  { id: "clay", hex: "#8C4A2F", ar: "طيني", en: "Clay" },
  { id: "steel", hex: "#3D4F63", ar: "فولاذي", en: "Steel" },
  { id: "ink", hex: "#1B2A41", ar: "حبري", en: "Ink" },
  { id: "bronze", hex: "#6B4A21", ar: "برونزي", en: "Bronze" },
  { id: "emerald", hex: "#0F5A45", ar: "زمردي", en: "Emerald" },
  { id: "mulberry", hex: "#6D2244", ar: "توتي", en: "Mulberry" },
  { id: "denim", hex: "#26456E", ar: "دنيم", en: "Denim" },
  { id: "umber", hex: "#5A3A22", ar: "بنّي داكن", en: "Umber" },
  { id: "juniper", hex: "#22503F", ar: "عرعري", en: "Juniper" },
  { id: "wine", hex: "#701F28", ar: "نبيذي", en: "Wine" },
];

export type PresetGroup =
  | "academic" | "modern" | "expressive" | "heritage" | "technical" | "english";

export interface Preset {
  id: string;
  /** Which shelf of the library this sits on, so 43 themes stay browsable. */
  group: PresetGroup;
  ar: string;
  en: string;
  theme: Omit<DocTheme, "preset">;
}

export const PRESETS: Preset[] = [
  {
    id: "classic",
    group: "academic",
    ar: "أكاديمي كلاسيكي",
    en: "Classic academic",
    theme: {
      accent: "#1F3864",
      headingFont: "naskh",
      bodyFont: "plex",
      fontSize: 12,
      lineHeight: 1.95,
      justify: true,
      headingRule: true,
      coverStyle: "centered",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "modern",
    group: "modern",
    ar: "حديث",
    en: "Modern",
    theme: {
      accent: "#0D6A6F",
      headingFont: "cairo",
      bodyFont: "plex",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: false,
      headingRule: false,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "thesis",
    group: "academic",
    ar: "رسالة علمية",
    en: "Thesis",
    theme: {
      accent: "#2E3440",
      headingFont: "naskh",
      bodyFont: "naskh",
      fontSize: 13,
      lineHeight: 2.1,
      justify: true,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "report",
    group: "technical",
    ar: "تقرير رسمي",
    en: "Formal report",
    theme: {
      accent: "#7B2D3B",
      headingFont: "tajawal",
      bodyFont: "tajawal",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: true,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "kufi",
    group: "expressive",
    ar: "كوفي معاصر",
    en: "Contemporary Kufi",
    theme: {
      accent: "#12506E",
      headingFont: "notokufi",
      bodyFont: "notosans",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "elegant",
    group: "expressive",
    ar: "أنيق",
    en: "Elegant",
    theme: {
      accent: "#5B2A6B",
      headingFont: "messiri",
      bodyFont: "almarai",
      fontSize: 11.5,
      lineHeight: 1.9,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "manuscript",
    group: "heritage",
    ar: "مخطوط",
    en: "Manuscript",
    theme: {
      accent: "#5F1F35",
      headingFont: "arefruqaa",
      bodyFont: "notonaskh",
      fontSize: 13,
      lineHeight: 2.05,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "minimal",
    group: "modern",
    ar: "مجرّد",
    en: "Minimal",
    theme: {
      accent: "#334155",
      headingFont: "alexandria",
      bodyFont: "alexandria",
      fontSize: 11,
      lineHeight: 1.8,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "vivid",
    group: "expressive",
    ar: "حيوي",
    en: "Vivid",
    theme: {
      accent: "#1D4ED8",
      headingFont: "changa",
      bodyFont: "readex",
      fontSize: 11,
      lineHeight: 1.75,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "narrow",
    },
  },
  {
    id: "scholarly",
    group: "academic",
    ar: "بحثي رصين",
    en: "Scholarly",
    theme: {
      accent: "#14532D",
      headingFont: "markazi",
      bodyFont: "scheherazade",
      fontSize: 13.5,
      lineHeight: 2.0,
      justify: true,
      headingRule: true,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "editorial",
    group: "expressive",
    ar: "تحريري",
    en: "Editorial",
    theme: {
      accent: "#8A3B12",
      headingFont: "reemkufi",
      bodyFont: "mada",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "clinical",
    group: "technical",
    ar: "تقني دقيق",
    en: "Clinical",
    theme: {
      accent: "#0E5C63",
      headingFont: "plex",
      bodyFont: "plex",
      fontSize: 10.5,
      lineHeight: 1.7,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "narrow",
    },
  },
  {
    id: "cairoclean",
    group: "modern",
    ar: "القاهرة النظيف",
    en: "Cairo clean",
    theme: {
      accent: "#3A3D8F",
      headingFont: "cairo",
      bodyFont: "cairo",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "beirut",
    group: "modern",
    ar: "بيروتي",
    en: "Beirut",
    theme: {
      accent: "#9B1C31",
      headingFont: "beiruti",
      bodyFont: "beiruti",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: false,
      headingRule: false,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "dissertation",
    group: "academic",
    ar: "أطروحة دكتوراه",
    en: "Dissertation",
    theme: {
      accent: "#1B2A41",
      headingFont: "notonaskh",
      bodyFont: "notonaskh",
      fontSize: 13,
      lineHeight: 2.15,
      justify: true,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "lecture",
    group: "expressive",
    ar: "عرض محاضرة",
    en: "Lecture",
    theme: {
      accent: "#26456E",
      headingFont: "kufam",
      bodyFont: "notosans",
      fontSize: 12,
      lineHeight: 1.85,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "journal",
    group: "academic",
    ar: "ورقة محكّمة",
    en: "Journal paper",
    theme: {
      accent: "#3D4F63",
      headingFont: "markazi",
      bodyFont: "notonaskh",
      fontSize: 11,
      lineHeight: 1.9,
      justify: true,
      headingRule: true,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "proposal",
    group: "academic",
    ar: "خطة بحث",
    en: "Research proposal",
    theme: {
      accent: "#0F5A45",
      headingFont: "messiri",
      bodyFont: "readex",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: true,
      headingRule: true,
      coverStyle: "centered",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "poster",
    group: "expressive",
    ar: "ملصق علمي",
    en: "Scientific poster",
    theme: {
      accent: "#4C2A85",
      headingFont: "lemonada",
      bodyFont: "zain",
      fontSize: 12,
      lineHeight: 1.7,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "narrow",
    },
  },
  {
    id: "heritage",
    group: "heritage",
    ar: "تراثي",
    en: "Heritage",
    theme: {
      accent: "#6B4A21",
      headingFont: "mirza",
      bodyFont: "lateef",
      fontSize: 13.5,
      lineHeight: 2.05,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "calligraphy",
    group: "heritage",
    ar: "خطّي",
    en: "Calligraphic",
    theme: {
      accent: "#6D2244",
      headingFont: "katibeh",
      bodyFont: "notonaskh",
      fontSize: 13,
      lineHeight: 2.0,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "quran",
    group: "academic",
    ar: "دراسات قرآنية",
    en: "Quranic studies",
    theme: {
      accent: "#22503F",
      headingFont: "alkalami",
      bodyFont: "scheherazade",
      fontSize: 14,
      lineHeight: 2.2,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "linguistics",
    group: "academic",
    ar: "دراسات لغوية",
    en: "Linguistics",
    theme: {
      accent: "#4A1D4E",
      headingFont: "gulzar",
      bodyFont: "lateef",
      fontSize: 13.5,
      lineHeight: 2.1,
      justify: true,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "softsans",
    group: "modern",
    ar: "سانس هادئ",
    en: "Soft sans",
    theme: {
      accent: "#3F5233",
      headingFont: "harmattan",
      bodyFont: "harmattan",
      fontSize: 12.5,
      lineHeight: 1.9,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "techreport",
    group: "technical",
    ar: "تقرير تقني",
    en: "Technical report",
    theme: {
      accent: "#334155",
      headingFont: "rubik",
      bodyFont: "rubik",
      fontSize: 10.5,
      lineHeight: 1.7,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "letter",
      margin: "narrow",
    },
  },
  {
    id: "startup",
    group: "expressive",
    ar: "عرض مشروع",
    en: "Project pitch",
    theme: {
      accent: "#1D4ED8",
      headingFont: "baloo",
      bodyFont: "rubik",
      fontSize: 11.5,
      lineHeight: 1.75,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "narrow",
    },
  },
  {
    id: "persian",
    group: "expressive",
    ar: "فارسي معاصر",
    en: "Persian modern",
    theme: {
      accent: "#8C4A2F",
      headingFont: "lalezar",
      bodyFont: "vazirmatn",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: false,
      headingRule: false,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "estedadclean",
    group: "modern",
    ar: "استعداد",
    en: "Estedad",
    theme: {
      accent: "#12506E",
      headingFont: "estedad",
      bodyFont: "estedad",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "fustatdoc",
    group: "modern",
    ar: "الفسطاط",
    en: "Fustat",
    theme: {
      accent: "#5A3A22",
      headingFont: "fustat",
      bodyFont: "fustat",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: true,
      headingRule: true,
      coverStyle: "centered",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "marhaba",
    group: "expressive",
    ar: "مرحى",
    en: "Marhey",
    theme: {
      accent: "#701F28",
      headingFont: "marhey",
      bodyFont: "zain",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "qahira",
    group: "modern",
    ar: "قاهري",
    en: "Qahiri",
    theme: {
      accent: "#2E3440",
      headingFont: "qahiri",
      bodyFont: "mada",
      fontSize: 11.5,
      lineHeight: 1.8,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
  {
    id: "ruwuducl",
    group: "academic",
    ar: "رُوودو",
    en: "Ruwudu",
    theme: {
      accent: "#1F5136",
      headingFont: "ruwudu",
      bodyFont: "ruwudu",
      fontSize: 13,
      lineHeight: 2.0,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "noble",
    group: "heritage",
    ar: "نبيل",
    en: "Noble",
    theme: {
      accent: "#701F28",
      headingFont: "rakkas",
      bodyFont: "notonaskh",
      fontSize: 13,
      lineHeight: 2.0,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "engclassic",
    group: "english",
    ar: "إنجليزي كلاسيكي",
    en: "English classic",
    theme: {
      accent: "#1F3864",
      headingFont: "ebgaramond",
      bodyFont: "ebgaramond",
      fontSize: 12,
      lineHeight: 1.9,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "normal",
    },
  },
  {
    id: "engthesis",
    group: "english",
    ar: "أطروحة إنجليزية",
    en: "English thesis",
    theme: {
      accent: "#2E3440",
      headingFont: "merriweather",
      bodyFont: "ptserif",
      fontSize: 11.5,
      lineHeight: 2.0,
      justify: true,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "wide",
    },
  },
  {
    id: "engmodern",
    group: "english",
    ar: "إنجليزي حديث",
    en: "English modern",
    theme: {
      accent: "#1D4ED8",
      headingFont: "inter",
      bodyFont: "inter",
      fontSize: 10.5,
      lineHeight: 1.7,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "letter",
      margin: "normal",
    },
  },
  {
    id: "engjournal",
    group: "english",
    ar: "دورية إنجليزية",
    en: "English journal",
    theme: {
      accent: "#3D4F63",
      headingFont: "notoserif",
      bodyFont: "notoserif",
      fontSize: 11,
      lineHeight: 1.85,
      justify: true,
      headingRule: true,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "normal",
    },
  },
  {
    id: "engeditorial",
    group: "english",
    ar: "تحريري إنجليزي",
    en: "English editorial",
    theme: {
      accent: "#5F1F35",
      headingFont: "playfair",
      bodyFont: "lora",
      fontSize: 11.5,
      lineHeight: 1.85,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "normal",
    },
  },
  {
    id: "engtech",
    group: "english",
    ar: "تقني إنجليزي",
    en: "English technical",
    theme: {
      accent: "#0E5C63",
      headingFont: "plexserif",
      bodyFont: "sourcesans",
      fontSize: 10.5,
      lineHeight: 1.7,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "narrow",
    },
  },
  {
    id: "engclean",
    group: "english",
    ar: "إنجليزي مجرّد",
    en: "English clean",
    theme: {
      accent: "#334155",
      headingFont: "worksans",
      bodyFont: "publicsans",
      fontSize: 10.5,
      lineHeight: 1.75,
      justify: false,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "letter",
      margin: "wide",
    },
  },
  {
    id: "engbook",
    group: "english",
    ar: "كتاب إنجليزي",
    en: "English book",
    theme: {
      accent: "#5A3A22",
      headingFont: "baskerville",
      bodyFont: "crimson",
      fontSize: 12,
      lineHeight: 1.95,
      justify: true,
      headingRule: false,
      coverStyle: "centered",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "wide",
    },
  },
  {
    id: "engbold",
    group: "english",
    ar: "إنجليزي جريء",
    en: "English bold",
    theme: {
      accent: "#8A3B12",
      headingFont: "robotoslab",
      bodyFont: "karla",
      fontSize: 11,
      lineHeight: 1.75,
      justify: false,
      headingRule: true,
      coverStyle: "band",
      tableStyle: "filled",
      pageSize: "letter",
      margin: "normal",
    },
  },
  {
    id: "engserene",
    group: "english",
    ar: "إنجليزي هادئ",
    en: "English serene",
    theme: {
      accent: "#22503F",
      headingFont: "spectral",
      bodyFont: "alegreya",
      fontSize: 11.5,
      lineHeight: 1.9,
      justify: true,
      headingRule: false,
      coverStyle: "minimal",
      tableStyle: "lines",
      pageSize: "a4",
      margin: "normal",
    },
  },
];



export const PRESET_GROUPS: { id: PresetGroup; ar: string; en: string }[] = [
  { id: "academic", ar: "أكاديمي", en: "Academic" },
  { id: "modern", ar: "حديث", en: "Modern" },
  { id: "expressive", ar: "تعبيري", en: "Expressive" },
  { id: "heritage", ar: "تراثي", en: "Heritage" },
  { id: "technical", ar: "تقني", en: "Technical" },
  { id: "english", ar: "إنجليزي", en: "English" },
];

export const DEFAULT_THEME: DocTheme = { preset: "classic", ...PRESETS[0].theme };

export function presetTheme(id: string): DocTheme {
  const preset = PRESETS.find((p) => p.id === id);
  return preset ? { preset: preset.id, ...preset.theme } : DEFAULT_THEME;
}

/** Page geometry in the units each exporter needs. */
export const PAGE = {
  a4: { css: "A4", widthMm: 210, heightMm: 297, twipsW: 11906, twipsH: 16838 },
  letter: { css: "Letter", widthMm: 216, heightMm: 279, twipsW: 12240, twipsH: 15840 },
} as const;

/** Margins in millimetres; Word wants twips (1mm = 56.7 twips). */
export const MARGINS = {
  narrow: 15,
  normal: 25,
  wide: 35,
} as const;

export const marginTwips = (margin: DocTheme["margin"]) =>
  Math.round(MARGINS[margin] * 56.7);

/** Hex without the leading # — the form Word and PowerPoint expect. */
export const bare = (hex: string) => hex.replace(/^#/, "").toUpperCase();

/** Mixes a colour towards white, for fills derived from the accent. */
export function tint(hex: string, amount: number): string {
  const value = hex.replace(/^#/, "");
  const to = (i: number) => parseInt(value.slice(i, i + 2), 16);
  const mix = (channel: number) => Math.round(channel + (255 - channel) * amount);
  const out = [mix(to(0)), mix(to(2)), mix(to(4))]
    .map((c) => c.toString(16).padStart(2, "0"))
    .join("");
  return out.toUpperCase();
}

/** The Google Fonts href a document needs for its chosen faces. */
export function fontsHref(theme: DocTheme): string {
  const families = [fontById(theme.headingFont), fontById(theme.bodyFont)]
    .map((f) => f.google)
    .filter((g, i, all): g is string => Boolean(g) && all.indexOf(g) === i);
  if (!families.length) return "";
  return `https://fonts.googleapis.com/css2?${families
    .map((f) => `family=${f}`)
    .join("&")}&display=swap`;
}
